### ISSUE TITLE
Home route flashing before restoration

### ISSUE THREAD

**Issue by leobasilio** [littlerobots/flutter-native-state#15]
Hi. I'm a new user, and I've noticed that the home route flashes for a few frames before state restoration. After investigating the source code for a while, I get it. The `MyApp` widget is built while a `Future` loads the saved state. The `Future` then completes and triggers a rebuild. I would like to avoid that. I already have a `main() async` to handle some other initialization. It makes the splash screen to persist until `runApp()` is called. So I thought I could load the saved state during this initialization and later feed it into the root `SavedState` widget. Something like this:

```dart
Future<void> main() async {
  final result = await Future.wait([
    SavedStateData.restore(),
    ...,
  ]);

  runApp(
    SavedState(
      savedState: result[0] as SavedStateData,
      child: MyApp(),
    ),
  );
}
```

It turns out that the default constructor doesn't accept a `savedState` argument, but we do have a `SavedState.value()` constructor that does. The problem is that it doesn't take the responsibility to clear the state once the widget is disposed. I'm not sure why is that, but, long story short, I ended up implementing my own version of the [`_SavedStateDisposer`](https://github.com/littlerobots/flutter-native-state/blob/064b4adb9ca33a8e1d6430e9c794680f7d5b2569/lib/src/widget.dart#L143) widget. Something like that:

```dart
runApp(
  WillDisposeScope(
    child: SavedState.value(
      savedState: savedState,
      child: MyApp(),
    ),
    onDispose: () {
      savedState.clear();
    },
  ),
);
```

It does work as intended, and it also avoids throwing away the old navigator once the state is loaded, so no `GlobalKey()` needed. I wonder if we could somehow incorporate that to this package. Maybe using a new constructor that would take that responsibility or a new widget like `_SavedStateDisposer` that would handle that. What are your thoughts?

![NativeState](https://user-images.githubusercontent.com/16745138/86625849-2aacea00-bf9c-11ea-9468-521a1a550aa3.gif)

**Comment by hvisser** [comment]
This kind of API is what I was trying to avoid, and is why I choose for rebuilding the tree, it feels more Flutter-like and gives a better API imho. Waiting for the state to load will also (slightly) delay start up time for the 99% case where state isn't available which is another reason that I'm not a big fan of this pattern. Rebuilding used to work without flickering or showing a black frame, but as Flutter advances this might not be the case anymore. I agree this is not great. Maybe we can delay the first paint in other ways?

`SaveState.value` doesn't manage the lifecycle of the state as documented, it's meant for passing around state that you might already have and want to manage yourself, like you are doing. Disposing will probably do not much anyway here, since what would mean the top level widget is disposed in your example.

The future code in your example can be simplified further too, you can just `await` `SavedState.restore()`.

The ideal solution would be keeping the API as is while eliminating the possible black frame, this would need a bit of investigation then.

**Comment by leobasilio** [comment]
I think the loading delay is negligible, and I don't know any other way to delay the first frame besides an async main. Even if there is one, we're going to end up displaying either the splash screen or a black frame, which has the same effect of what I'm doing. Perhaps another approach could be to build some sort of loading screen and build `MaterialApp` only when the state is restored. The final affect is almost the the same, but it's more Flutter-like, as you say. There could be `FutureBuilder` alike widget, but for the state.

The Future in my code can't be simplified because there are other Futures I'm awaiting. I've just omitted them using "...".

I'm happy with my "workaround" for now, so there's no need to go deeper into this issue. I just wanted to bring some attention to this problem.

**Comment by hvisser** [comment]
OK, cool, I'll just keep this open for a bit. I think the `await`ing `SavedState.restore()` and then passing it to your app would be the current workaround in the mean time.
