### ISSUE TITLE
How to use with onGenerateRoute?

### ISSUE THREAD

**Issue by rahuldange09** [littlerobots/flutter-native-state#9]
How to use with onGenerateRoute: RouteGenerater.generateRoute.
It's not working with it. Is there any way to do with onGenerateRoute?

**Comment by hvisser** [comment]
AFAIK if you generate the routes using a function this should still work, but you have to make sure that all routes in the hierarchy resolve correctly, so I suspect your generating function isn't generating the routes correctly, therefore not restoring the route. This is also independent of this plugin by the way, the Navigator will always restore the routes based in the `initialRoute` property.

If you have an example project that demonstrates the issue I can take a look.

**Comment by rahuldange09** [comment]
Thanks for response. 
Please take a look how i'm doing

**main.dart**
```
MaterialApp(
...
 initialRoute: SavedStateRouteObserver.restoreRoute(savedState) ?? "/",
 onGenerateRoute: RouteGenerater.generateRoute,
 navigatorKey: GlobalKey(),
 navigatorObservers: [ SavedStateRouteObserver(savedState: SavedState.of(context)) ],
)
```
**my_routes.dart**

```
class RouteGenerater {
  static const ROUTE_HOME = "/home";
  static const ROUTE_SEARCH = "/search";

static Route<dynamic> generateRoute(RouteSettings settings) {
    switch (settings.name) {
      case ROUTE_HOME:
        final page = HomeScreen(settings.arguments);
        return MaterialPageRoute(builder: (context) => page);

      case ROUTE_SEARCH:
        final page = SearchScreen();
        return MaterialPageRoute(builder: (context) => page);

      default:
         return MaterialPageRoute(builder: (context) => LoginScreen());
    }
  }

}
```

**And then calling normally**
```
Navigator.of(context).pushNamed("routeName");
```

**Comment by hvisser** [comment]
So does this work if you hardcode your `initialRoute` here? All the plugin does here is provide the saved route name if there is any so in that sense this is mostly about the built in `Navigator` class. 

Hardcoding the route will check if restoration works (looking at your example it should). 

If that works, then you need to change how you are setting up the `SavedState` here; you can either wrap your whole app in a `SavedState` widget or lift out the `SavedState.of(context)` to a variable like in https://github.com/littlerobots/flutter-native-state/blob/develop/example/lib/main.dart since it might be that the widget doesn't get rebuild correctly when the state is loaded. It's hard to tell without a working project though.

**Comment by rahuldange09** [comment]
I tried hardcoding  the route  and it does work as u said.
And yes i have wrapped whole app in 
`SavedState(child : MyApp())`
But still no luck with normal flow. Works with hardcoded one though.

**Comment by hvisser** [comment]
If you can create a small project that reproduces the issue I'll take a look. Otherwise you should take another look at the examples to see what's different to your setup. It looks like the route name isn't stored or restored from the saved state.

How Flutter rebuilds the widgets can be tricky, as I mentioned you may beed to lift out `SavedState.of(context)` out to a variable like in the example.

**Comment by rahuldange09** [comment]
Well i created a sample project from your example project and added GenerateRoutes in it.
Please have a look at it.
https://github.com/rahuldange09/flutter_test_state

**Comment by hvisser** [comment]
Thanks, that helped me to figure it out. `SavedStateRouteObserver` uses the route name from the route `RouteSettings`. Since you are not passing any `RouteSettings` the name will always be `null` and therefore the root `/` route is always selected. Effectively no route name is ever stored because the routes are not providing their name to the navigation observer.

If you return the route like this `MaterialPageRoute(builder: (context) => page, settings: RouteSettings(name: ROUTE_HOME));` it will work, as the route will now have a proper name reflected in the settings. 

All in all for routes that you need to restore like this, it probably makes more sense to use named routes since they are fixed to the application anyway, this saves you specifying the route name everywhere. `onGenerateRoute` is more suitable for dynamic routes.

**Comment by rahuldange09** [comment]
> Thanks, that helped me to figure it out. `SavedStateRouteObserver` uses the route name from the route `RouteSettings`. Since you are not passing any `RouteSettings` the name will always be `null` and therefore the root `/` route is always selected. Effectively no route name is ever stored because the routes are not providing their name to the navigation observer.
> 
> If you return the route like this `MaterialPageRoute(builder: (context) => page, settings: RouteSettings(name: ROUTE_HOME));` it will work, as the route will now have a proper name reflected in the settings.
> 
> All in all for routes that you need to restore like this, it probably makes more sense to use named routes since they are fixed to the application anyway, this saves you specifying the route name everywhere. `onGenerateRoute` is more suitable for dynamic routes.

Sorry for late response.
Thank you for taking time and helping out.
It works now. 
have a little issue but i think I can fix it.

well i must say this is must plugin for every flutter project.
80% are not aware of this issue in flutter.
And this plugin is great to solve it.
